// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tienda.API.Modelos;

#nullable disable

namespace Tienda.API.Migrations
{
    [DbContext(typeof(ProductosDbContext))]
    [Migration("20230310082948_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Tienda.API.Modelos.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Marca = "ToTo",
                            NombreProducto = "Camisa",
                            Precio = 40.0
                        },
                        new
                        {
                            Id = 2,
                            Marca = "Nike",
                            NombreProducto = "Zapatilla",
                            Precio = 120.0
                        },
                        new
                        {
                            Id = 3,
                            Marca = "Zhara",
                            NombreProducto = "Sueter",
                            Precio = 200.0
                        },
                        new
                        {
                            Id = 4,
                            Marca = "Pull&Bear",
                            NombreProducto = "Pantalon",
                            Precio = 50.0
                        },
                        new
                        {
                            Id = 5,
                            Marca = "Paito",
                            NombreProducto = "Saco",
                            Precio = 120.0
                        },
                        new
                        {
                            Id = 6,
                            Marca = "Venus",
                            NombreProducto = "Zapatos",
                            Precio = 30.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
